### ISSUE TITLE
db-url is parsed incorrectly

### ISSUE THREAD

**Issue by icassina** [xebialabs-community/xl-ci-tool#2]
given this file:

```
xl {
    database {
        db-driver-classname="com.microsoft.sqlserver.jdbc.SQLServerDriver"
        db-password=database
        db-url="jdbc:sqlserver://myhost:1433;databaseName=mydatabase_test"
        db-username=database
    }
    reporting {
        db-driver-classname="com.microsoft.sqlserver.jdbc.SQLServerDriver"
        db-password=reporting
        db-url="jdbc:sqlserver://myhost:1433;databaseName=myreporting_test"
        db-username=reporting
    }
}
```
The tool will fail to parse db-url correctly:

```
D:\temp>java -jar xl_ci_tool_exec-1.2.1.jar -f xlr-jira-mapping.json -i D:\SrvApps\Xebia\xl-release-9.0.2-server -preview
Beginning Migration
Preview has been set. Application will preview the results of the mapping actions but will not change the database.
Configuration is complete. The following values will be used: system = XLR, dbType = SQLSERVER, dbDriver = com.microsoft.sqlserver.jdbc.SQLServerDriver, dbUrl
= mydatabase_test, dbUsername = database, dbPwd = Using Default, reportDbType = SQLSERVER, reportDbDriver = com.microsoft.sqlserver.jdbc.SQLServerDriver, r
eportDdbUrl = myreporting_, reportDbUsername = reporting, reportDbPwd = Using Default
Connecting to database...
java.sql.SQLException: No suitable driver found for mydatabase_test
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at com.xebialabs.migration.Migration.main(Migration.java:190)
```

Expected:

db-url are correctly parsed to ""jdbc:sqlserver://myhost:1433;databaseName=mydatabase_test" and "jdbc:sqlserver://myhost:1433;databaseName=myreporting_test"

Fix:

do *not* call `cleanValue` in https://github.com/xebialabs-community/xl-ci-tool/blob/master/src/main/java/com/xebialabs/migration/parser/MigrationConfigParser.java#L129

**Comment by magichome** [comment]
Code updated.  Please verify the fix works in the above situation.

**Comment by ladamato** [comment]
Closing this, assume fix worked.
